package com.healthcare.portal.controller;
import com.healthcare.portal.entity.*; import com.healthcare.portal.repository.*; import io.swagger.v3.oas.annotations.Operation; import io.swagger.v3.oas.annotations.tags.Tag; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import java.math.BigDecimal; import java.util.*; import com.healthcare.portal.security.CustomUserDetails;
@RestController @RequestMapping("/api/clinical") @Tag(name="Clinical Operations",description="Laboratory, insurance and patient consent workflows")
public class ClinicalOperationsController { private final LabOrderRepository labs; private final InsuranceClaimRepository claims; private final ConsentRepository consents; private final UserRepository users; private final AppointmentRepository appointments;
 public ClinicalOperationsController(LabOrderRepository l,InsuranceClaimRepository c,ConsentRepository co,UserRepository u,AppointmentRepository a){labs=l;claims=c;consents=co;users=u;appointments=a;}
 private Map<String,Object> labView(LabOrder x){Map<String,Object> m=new LinkedHashMap<>();m.put("id",x.getId());m.put("patientId",x.getPatient().getId());m.put("testName",x.getTestName());m.put("status",x.getStatus());m.put("amount",x.getAmount());m.put("reportUrl",x.getReportUrl());m.put("createdAt",x.getCreatedAt());return m;}
 private Map<String,Object> claimView(InsuranceClaim x){Map<String,Object> m=new LinkedHashMap<>();m.put("id",x.getId());m.put("patientId",x.getPatient().getId());m.put("appointmentId",x.getAppointment()==null?null:x.getAppointment().getId());m.put("provider",x.getProvider());m.put("policyNumber",x.getPolicyNumber());m.put("amount",x.getAmount());m.put("status",x.getStatus());m.put("notes",x.getNotes());m.put("createdAt",x.getCreatedAt());return m;}
 @PostMapping("/lab-orders") @Operation(summary="Create a laboratory test order") public Map<String,Object> lab(@RequestParam Long patientId,@RequestParam String testName,@RequestParam(defaultValue="0") BigDecimal amount){User p=users.findById(patientId).orElseThrow(); return labView(labs.save(new LabOrder(p,null,testName,amount)));}
 @PatchMapping("/lab-orders/{id}/report") public Map<String,Object> report(@PathVariable Long id,@RequestParam String reportUrl,@RequestParam(defaultValue="COMPLETED") String status){LabOrder l=labs.findById(id).orElseThrow();l.setReportUrl(reportUrl);l.setStatus(status);return labView(labs.save(l));}
 @PostMapping("/insurance-claims") public Map<String,Object> claim(@RequestParam Long patientId,@RequestParam(required=false) Long appointmentId,@RequestParam String provider,@RequestParam String policyNumber,@RequestParam BigDecimal amount,@RequestParam(required=false) String notes){User p=users.findById(patientId).orElseThrow();Appointment a=appointmentId==null?null:appointments.findById(appointmentId).orElseThrow();return claimView(claims.save(new InsuranceClaim(p,a,provider,policyNumber,amount,notes)));}
 @PatchMapping("/insurance-claims/{id}/status") public Map<String,Object> claimStatus(@PathVariable Long id,@RequestParam String status){InsuranceClaim c=claims.findById(id).orElseThrow();c.setStatus(status);return claimView(claims.save(c));}
 @PostMapping("/consents") public Map<String,Object> consent(@RequestParam Long patientId,@RequestParam String consentType,@RequestParam boolean granted,@RequestParam(required=false) String purpose){User p=users.findById(patientId).orElseThrow();Consent c=consents.findAll().stream().filter(x->x.getPatient().getId().equals(patientId)&&x.getConsentType().equals(consentType)).findFirst().map(x->{x.setGranted(granted);return consents.save(x);}).orElseGet(()->consents.save(new Consent(p,consentType,granted,purpose)));return Map.of("id",c.getId(),"patientId",patientId,"consentType",c.getConsentType(),"granted",c.isGranted(),"purpose",String.valueOf(c.getPurpose()),"updatedAt",c.getUpdatedAt());}
 @GetMapping("/consents/me") public List<Map<String,Object>> myConsents(@AuthenticationPrincipal CustomUserDetails u){return consents.findAll().stream().filter(x->x.getPatient().getId().equals(u.getId())).map(x->Map.<String,Object>of("id",x.getId(),"consentType",x.getConsentType(),"granted",x.isGranted(),"purpose",String.valueOf(x.getPurpose()),"updatedAt",x.getUpdatedAt())).toList();}
}
